CREATE TABLE `USERS` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT
  , `EMAIL` VARCHAR(20) NOT NULL
  , `PASSWORD` VARCHAR(60) NOT NULL
  , `CREATION_TIME` TIMESTAMP NOT NULL
  , PRIMARY KEY (`ID`)
);

CREATE TABLE `IDEAS` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT
  , `TITLE` VARCHAR(150) NOT NULL
  , `DESCRIPTION` VARCHAR(300) NOT NULL
  , `CREATION_TIME` TIMESTAMP NOT NULL
  , `MODIFICATION_TIME` TIMESTAMP NOT NULL
  , `RATING` INT NOT NULL
  , `USER_ID` BIGINT NOT NULL
  , PRIMARY KEY (`ID`)
  , CONSTRAINT `IDEAS_fk1` FOREIGN KEY (`USER_ID`) REFERENCES USERS(`ID`)
);

CREATE TABLE `ROLES` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT
  , `NAME` VARCHAR(10) NOT NULL
  , PRIMARY KEY (`ID`)
);

CREATE TABLE `USER_ROLES` (
  `USER_ID` BIGINT NOT NULL
  , `ROLE_ID` BIGINT NOT NULL
  , PRIMARY KEY (`USER_ID`,`ROLE_ID`)
  , CONSTRAINT `USER_ROLES_fk1` FOREIGN KEY (`USER_ID`) REFERENCES USERS(`ID`)
  , CONSTRAINT `USER_ROLES_fk2` FOREIGN KEY (`ROLE_ID`) REFERENCES ROLES(`ID`)
);

CREATE TABLE `TAGS` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT
  , `NAME` VARCHAR(20) NOT NULL
  , PRIMARY KEY (`ID`)
);

CREATE TABLE `IDEA_TAGS` (
  `IDEA_ID` BIGINT NOT NULL
  , `TAG_ID` BIGINT NOT NULL
  , PRIMARY KEY (`IDEA_ID`,`TAG_ID`)
  , CONSTRAINT `IDEA_TAGS_fk1` FOREIGN KEY (`IDEA_ID`) REFERENCES IDEAS(`ID`)
  , CONSTRAINT `IDEA_TAGS_fk2` FOREIGN KEY (`TAG_ID`) REFERENCES TAGS(`ID`)
);

CREATE TABLE `COMMENTS` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT
  , `USER_ID` BIGINT NOT NULL
  , `IDEA_ID` BIGINT NOT NULL
  , `BODY` VARCHAR(300) NOT NULL
  , `CREATION_TIME` TIMESTAMP NOT NULL
  , `MODIFICATION_TIME` TIMESTAMP NOT NULL
  , `RATING` INT NOT NULL
  , PRIMARY KEY (`ID`)
  , CONSTRAINT `COMMENTS_fk1` FOREIGN KEY (`USER_ID`) REFERENCES USERS(`ID`)
  , CONSTRAINT `COMMENTS_fk2` FOREIGN KEY (`IDEA_ID`) REFERENCES IDEAS(`ID`)
);